# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: CI

on:
  push:
    branches:
      - **
    tags-ignore:
      - **

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn verify assembly:single

    - name: Get app distribution artifact name
      id: artifact_name
      run: cd target && echo "artifact_name=$(ls -1 *.tar.gz)" >> "$GITHUB_OUTPUT"      

    - name: Upload app distribution artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.artifact_name.outputs.artifact_name }}
        path: target/${{ steps.artifact_name.outputs.artifact_name }}
