name: on-main

on:
  push:
    branches:
      - main
  workflow_call:
    secrets:
      TOP_SECRET:
        required: true


jobs:
  syncTestReports:
    runs-on: ubuntu-22.04
    steps:
      - name: Get Unit Test Reports
        uses: dawidd6/action-download-artifact@e7466d1a7587ed14867642c2ca74b5bcc1e19a2d
        with:
          workflow: test.yml
          workflow_conclusion: success
          pr: ${{github.event.pull_request.number}}
          name_is_regexp: true
          name: 'unit-.*-test-results'
          path: unit-test-results
          if_no_artifact_found: true
      - name: List files pre
        run: ls -lR
      - name: Upload Unit Test Results
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3
        with:
          name: unit-all-test-results
          path: 'unit-test-results/**/test-results/**/TEST-*.xml'
      - name: List files post
        run: ls -lR