# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Get the version
      id: get_version
      run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> "$GITHUB_OUTPUT"

    - name: Build with Maven
      run: mvn -Drevision="${{ steps.get_version.outputs.VERSION }}" verify assembly:single

    - name: Get app distribution artifact name
      id: artifact_name
      run: cd target && echo "ARTIFACT_NAME=$(ls -1 *.tar.gz)" >> "$GITHUB_OUTPUT"

    - name: Draft Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: 'Draft release of version ${{ steps.get_version.outputs.VERSION }}.'
        draft: true
        prerelease: false      

    - name: Upload release artifact
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: target/${{ steps.artifact_name.outputs.ARTIFACT_NAME }}
        asset_name: ${{ steps.artifact_name.outputs.ARTIFACT_NAME }}
        asset_content_type: application/octet-stream